// @ts-check
import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { NativeRoomStore } from '../src/native-store.mjs';

// Captured from unchanged 08fdbfb, not regenerated by the candidate's helpers.
const ROOM = '1'.repeat(32), EPOCH = '2'.repeat(32);
const FRAME_HASH = '6074e0feb3e36144e5b231f57f66192e534d1ba45d7a2f1486f203451fe3ddb6';
const MESSAGE_ID = '83f06ed7d2b3c68f92a935baad06c9ac03a3619d66cb731df94f76672234a3af';
const PAYLOAD_DIGEST = 'sha256:0b77385679ac77e54849415ad9739b77871008abb7fddca2ee04e707df02b6d5';
const RECORD_DIGEST = 'sha256:1c2ac27e86333786784fc8a194d822095d63d2a167fa578725e24d837fa34176';

test('new contracts leave the complete v1 frame, historical attachments and retry identity byte-identical', async () => {
  const root = await mkdtemp(path.join(tmpdir(), 'agora-p3-v1-'));
  /** @type {NativeRoomStore | undefined} */ let store;
  try {
    store = await NativeRoomStore.create({root, roomId: ROOM, epoch: EPOCH,
      hostAccountId: 'host_account_0001', now: () => new Date('2026-09-05T00:00:00.000Z')});
    const input = {operationId: 'operation_golden_01', authorName: '  Peer/agent  ',
      text: 'line 1\r\nline 2\\n e\u0301  ', attachments: [{id: 'attachment_000001', name: 'old.bin',
        kind: 'file', digest: `sha256:${'3'.repeat(64)}`, size: 7, mimetype: 'application/octet-stream'}]};
    const first = await store.append(input, {accountId: 'peer_account_0001'});
    assert.deepEqual(first, {id: MESSAGE_ID, cursor: `${EPOCH}:1`, duplicate: false});
    const before = await readFile(store.logPath);
    assert.equal(createHash('sha256').update(before).digest('hex'), FRAME_HASH);
    assert.equal(store.records[0].payloadDigest, PAYLOAD_DIGEST);
    assert.equal(store.records[0].recordDigest, RECORD_DIGEST);
    assert.deepEqual(store.checkpoint(), {roomId: ROOM, epoch: EPOCH, sequence: 1, digest: RECORD_DIGEST});
    const message = store.read()[0];
    assert.equal(message.text, input.text);
    assert.equal(Object.hasOwn(message.attachments[0], 'lifetime'), false);
    await store.close();
    store = await NativeRoomStore.open({root, roomId: ROOM});
    assert.deepEqual(store.read()[0], message);
    assert.deepEqual(await store.append(input, {accountId: 'peer_account_0001'}), {...first, duplicate: true});
    assert.deepEqual(await readFile(store.logPath), before);
  } finally {
    if (store) await store.close();
    await rm(root, {recursive: true, force: true});
  }
});
