#!/usr/bin/env bun
// Regenerates src/native-cursor.kernel.mjs from spec/cursor.bend through the Bend
// compiler's JS library emitter, after proving spec/PROOF.bend. The generated file
// is plain JavaScript with no imports, so the CLI keeps zero runtime dependencies;
// the Bend checkout is a build-time tool only.
//
//   BEND_CLONE=<path to a bendlang/bend checkout> bun spec/build-kernel.ts [--check]
//
// --check regenerates into memory and exits 1 when the committed file differs.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CLONE = process.env.BEND_CLONE ?? resolve(ROOT, "..", "bend-src");
const OUT = join(ROOT, "src", "native-cursor.kernel.mjs");
const KERNEL = join(ROOT, "spec", "cursor.bend").replaceAll("\\", "/");
const PROOF = join(ROOT, "spec", "PROOF.bend").replaceAll("\\", "/");
const MAIN = join(CLONE, "bend2", "main.ts").replaceAll("\\", "/");

if (!existsSync(MAIN)) {
  console.error(`no Bend checkout at ${CLONE}; set BEND_CLONE`);
  process.exit(2);
}

// the gate: the checker's stdout must be exactly the green string
const gate = spawnSync("bun", [MAIN, PROOF], { encoding: "utf8", env: { ...process.env, BEND_HUB: "http://127.0.0.1:1" } });
const verdict = ((gate.stdout ?? "") + (gate.stderr ?? "")).trim();
if (verdict !== "All terms check.") {
  console.error(`spec/PROOF.bend is not green:\n${verdict}`);
  process.exit(1);
}
for (const f of [KERNEL, PROOF, join(ROOT, "spec", "LAWS.bend")]) {
  if (/@unsafe|\?TODO|import 0x/.test(readFileSync(f, "utf8"))) {
    console.error(`${f} opts out of the proof (@unsafe, ?TODO or a hash import)`);
    process.exit(1);
  }
}

const Bend = await import(join(CLONE, "bend2", "bend.ts").replaceAll("\\", "/"));
const Comp = await import(join(CLONE, "bend2", "comp.ts").replaceAll("\\", "/"));
const book = Bend.book_nil();
await Bend.book_load(book, KERNEL, "", new Map());
Bend.book_valid(book, 0);
const outs = ([...new Set(book.order)] as string[]).filter((k) => {
  const t = book.tlds[k];
  return t.$ === "Def" && t.v !== null && t.b !== true && t.i === undefined && Comp.io_base(book, t.T) === null;
});
const header = [
  "// @ts-nocheck: generated code, not type-checked; the source is proved instead.",
  "// GENERATED by spec/build-kernel.ts from spec/cursor.bend; do not edit.",
  "// The laws in spec/LAWS.bend are proved over that source by the Bend 2 checker",
  "// (spec/PROOF.bend, gate string `All terms check.`) before this file is emitted.",
  `// Bend 2; exports: ${outs.join(", ")}.`,
  "",
].join("\n");
const js = header + Comp.js_lib(book, outs, outs);

if (process.argv.includes("--check")) {
  const committed = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (committed !== js) {
    console.error(`${OUT} differs from a fresh regeneration of spec/cursor.bend`);
    process.exit(1);
  }
  console.log(`ok   ${OUT} matches spec/cursor.bend (proof green)`);
} else {
  writeFileSync(OUT, js);
  console.log(`wrote ${OUT} (${js.length} bytes; exports ${outs.join(", ")})`);
}
