#!/usr/bin/env bun
// Regenerates a vendored kernel (src/native-<name>.kernel.mjs) from its Bend source
// through the Bend compiler's JS library emitter, after proving its laws. The generated
// file is plain JavaScript with no imports, so the CLI keeps zero runtime dependencies;
// the Bend checkout is a build-time tool only.
//
//   BEND_CLONE=<path to a bendlang/bend checkout> bun spec/build-kernel.ts [--spec <name>] [--check]
//
// Kernels: `cursor` (spec/cursor.bend, laws spec/LAWS.bend, proof spec/PROOF.bend) and
// `board` (spec/board.bend, spec/BOARD-LAWS.bend, spec/BOARD-PROOF.bend). No --spec
// regenerates every kernel. --check regenerates into memory and exits 1 when a committed
// file differs.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CLONE = process.env.BEND_CLONE ?? resolve(ROOT, "..", "bend-src");
const MAIN = join(CLONE, "bend2", "main.ts").replaceAll("\\", "/");

const KERNELS: Record<string, { source: string; laws: string; proof: string; out: string }> = {
  cursor: { source: "spec/cursor.bend", laws: "spec/LAWS.bend", proof: "spec/PROOF.bend", out: "src/native-cursor.kernel.mjs" },
  board: { source: "spec/board.bend", laws: "spec/BOARD-LAWS.bend", proof: "spec/BOARD-PROOF.bend", out: "src/native-board.kernel.mjs" },
};

const args = process.argv.slice(2);
const check = args.includes("--check");
const specAt = args.indexOf("--spec");
const names = specAt >= 0 ? [args[specAt + 1]] : Object.keys(KERNELS);
for (const n of names) if (!KERNELS[n]) { console.error(`unknown kernel ${n}; known: ${Object.keys(KERNELS).join(", ")}`); process.exit(2); }

if (!existsSync(MAIN)) {
  console.error(`no Bend checkout at ${CLONE}; set BEND_CLONE`);
  process.exit(2);
}

const Bend = await import(join(CLONE, "bend2", "bend.ts").replaceAll("\\", "/"));
const Comp = await import(join(CLONE, "bend2", "comp.ts").replaceAll("\\", "/"));

let failed = false;
for (const name of names) {
  const k = KERNELS[name];
  const source = join(ROOT, k.source).replaceAll("\\", "/");
  const proof = join(ROOT, k.proof).replaceAll("\\", "/");
  const out = join(ROOT, k.out);

  // the gate: the checker's stdout must be exactly the green string
  const gate = spawnSync("bun", [MAIN, proof], { encoding: "utf8", env: { ...process.env, BEND_HUB: "http://127.0.0.1:1" } });
  const verdict = ((gate.stdout ?? "") + (gate.stderr ?? "")).trim();
  if (verdict !== "All terms check.") {
    console.error(`${k.proof} is not green:\n${verdict}`);
    failed = true;
    continue;
  }
  let optedOut = false;
  for (const f of [k.source, k.laws, k.proof]) {
    if (/@unsafe|\?TODO|import 0x/.test(readFileSync(join(ROOT, f), "utf8"))) {
      console.error(`${f} opts out of the proof (@unsafe, ?TODO or a hash import)`);
      optedOut = true;
    }
  }
  if (optedOut) { failed = true; continue; }

  const book = Bend.book_nil();
  await Bend.book_load(book, source, "", new Map());
  Bend.book_valid(book, 0);
  const outs = ([...new Set(book.order)] as string[]).filter((key) => {
    const t = book.tlds[key];
    return t.$ === "Def" && t.v !== null && t.b !== true && t.i === undefined && Comp.io_base(book, t.T) === null;
  });
  const header = [
    "// @ts-nocheck: generated code, not type-checked; the source is proved instead.",
    `// GENERATED by spec/build-kernel.ts from ${k.source}; do not edit.`,
    `// The laws in ${k.laws} are proved over that source by the Bend 2 checker`,
    `// (${k.proof}, gate string \`All terms check.\`) before this file is emitted.`,
    `// Bend 2; exports: ${outs.join(", ")}.`,
    "",
  ].join("\n");
  const js = header + Comp.js_lib(book, outs, outs);

  if (check) {
    const committed = existsSync(out) ? readFileSync(out, "utf8") : "";
    if (committed !== js) {
      console.error(`${k.out} differs from a fresh regeneration of ${k.source}`);
      failed = true;
    } else {
      console.log(`ok   ${k.out} matches ${k.source} (proof green)`);
    }
  } else {
    writeFileSync(out, js);
    console.log(`wrote ${k.out} (${js.length} bytes; exports ${outs.join(", ")})`);
  }
}
process.exit(failed ? 1 : 0);
