// @ts-nocheck: generated code, not type-checked; the source is proved instead.
// GENERATED by spec/build-kernel.ts from spec/cursor.bend; do not edit.
// The laws in spec/LAWS.bend are proved over that source by the Bend 2 checker
// (spec/PROOF.bend, gate string `All terms check.`) before this file is emitted.
// Bend 2; exports: plan.same, plan, next, delivered.
function word_to_u32(w) {
  let x = 0;
  for (let i = 0; w.$ === "WCon"; i++) {
    x |= Number(w.head) << i;
    w = w.tail;
  }
  return x >>> 0;
}

function u32_to_word(x) {
  let w = {$: "WNil"};
  for (let i = 31; i >= 0; i--) {
    w = {$: "WCon", head: ((x >>> i) & 1) === 1, tail: w};
  }
  return w;
}

function cmp_new(a, b) {
  return {$: a < b ? "LT"
    : a === b ? "EQ" : "GT"};
}

function nat_divmod(a, b) {
  return b === 0n ? {$: "Tuple", fst: 0n, snd: a}
    : {$: "Tuple", fst: a / b, snd: a % b};
}

function nat_chk(n) {
  if (n > 281474976710655n) {
    throw "bend: a Nat past the largest immediate 2^48-1";
  }
  return n;
}

function f32_show(x) {
  if (x !== x) {
    return "nan";
  }
  if (!Number.isFinite(x) || Object.is(x, -0)) {
    return x < 0 ? "-inf"
      : x === 0 ? "-0" : "inf";
  }
  let s = "x";
  for (let p = 1; p <= 9 && Math.fround(Number(s)) !== x; p += 1) {
    s = String(Number(x.toExponential(p - 1)));
  }
  return s;
}

function f32_bits(x) {
  return new Uint32Array(new Float32Array([x]).buffer)[0];
}

function f32_from_bits(u) {
  return new Float32Array(new Uint32Array([u]).buffer)[0];
}

function f32_read(s) {
  const re = /^\s*[+-]?((\d+\.?\d*|\.\d+)(e[+-]?\d+)?|inf(inity)?|nan)$/i;
  const v = Number(s.replace(/inf\w*/i, "Infinity"));
  return re.test(s) ? {$: "Some", value: Math.fround(v)} : {$: "None"};
}

function char_new(code) {
  if (code > 0x10FFFF || (code >= 0xD800 && code <= 0xDFFF)) {
    throw "bend: " + code + " is not a Unicode scalar value";
  }
  return String.fromCodePoint(code);
}

// Array
// =====

function array_new(d, v) {
  if (d > 31n) {
    throw "bend: an array past the deepest block class 31";
  }
  return Array(2 ** Number(d)).fill(v);
}

// An unbalanced tree fails, as in C.
function array_node(a, b) {
  if (a.length !== b.length) {
    throw "bend: runtime fail-stop";
  }
  return a.concat(b);
}

function array_swap(a, i, v) {
  const at = i % a.length;
  const old = a[at];
  a[at] = v;
  return {$: "Tuple", fst: a, snd: old};
}

// Run
// ===

function run_jump(f, x) {
  return {$: "$JMP", f: f, x: x};
}

function run_tail(f, x) {
  return {$: "$JMP", f: f.j?.f === f ? f.j : f, x: [x]};
}

function run_clo(j) {
  const f = (x) => run_loop(j(x));
  f.j = j;
  j.f = f;
  return f;
}

function run_loop(r) {
  while (r !== null && typeof r === "object" && r.$ === "$JMP") {
    r = r.f(...r.x);
  }
  return r;
}

function run_lib(f, n) {
  return (...a) => a.length < n ? run_lib((...b) => f(...a, ...b), n - a.length)
    : run_loop(f(...a));
}
// Program
// =======

function $plan$same$(committed_0, since_0, limit_0, future_0) {
  if (future_0) {
    return {$: "RefusedFuture"};
  } else {
    return {$: "Slice", ["from"]: nat_chk(since_0 + 1n), ["to"]: run_loop($Nat$min$(nat_chk(since_0 + limit_0), committed_0))};
  }
}

function $plan$(same_epoch_0, committed_0, since_0, limit_0) {
  if (!same_epoch_0) {
    return {$: "RefusedEpoch"};
  } else {
    return run_jump($plan$same$, [committed_0, since_0, limit_0, run_loop($Nat$is_gt$(since_0, committed_0))]);
  }
}

function $next$(since_0, p_0) {
  if (p_0.$ === "RefusedEpoch") {
    return since_0;
  } else if (p_0.$ === "RefusedFuture") {
    return since_0;
  } else {
    const from_0 = p_0.from;
    const to_0 = p_0.to;
    return run_jump($Bool$pick$, [run_loop($Nat$is_gt$(from_0, to_0)), since_0, to_0]);
  }
}

function $delivered$(p_0) {
  if (p_0.$ === "RefusedEpoch") {
    return 0n;
  } else if (p_0.$ === "RefusedFuture") {
    return 0n;
  } else {
    const from_0 = p_0.from;
    const to_0 = p_0.to;
    return run_jump($Bool$pick$, [run_loop($Nat$is_gt$(from_0, to_0)), 0n, nat_chk((to_0 < from_0 ? 0n : to_0 - from_0) + 1n)]);
  }
}

function $Nat$min$(a_0, b_0) {
  return run_jump($Bool$pick$, [(a_0 < b_0), a_0, b_0]);
}

function $Nat$is_gt$(a_0, b_0) {
  return run_jump($Cmp$is_gt$, [cmp_new(a_0, b_0)]);
}

function $Bool$pick$(c_0, a_0, b_0) {
  if (!c_0) {
    return b_0;
  } else {
    return a_0;
  }
}

function $Cmp$is_gt$(c_0) {
  if (c_0.$ === "LT") {
    return false;
  } else if (c_0.$ === "EQ") {
    return false;
  } else {
    return true;
  }
}
export default {
  "plan.same": run_lib($plan$same$, 4),
  "plan": run_lib($plan$, 4),
  "next": run_lib($next$, 2),
  "delivered": run_lib($delivered$, 1),
};
