// @ts-nocheck: generated code, not type-checked; the source is proved instead.
// GENERATED by spec/build-kernel.ts from spec/board.bend; do not edit.
// The laws in spec/BOARD-LAWS.bend are proved over that source by the Bend 2 checker
// (spec/BOARD-PROOF.bend, gate string `All terms check.`) before this file is emitted.
// Bend 2; exports: live, owns, fence_of, judge.claim, judge.owned, judge.break, judge, after.
function word_to_u32(w) {
  let x = 0;
  for (let i = 0; w.$ === "WCon"; i++) {
    x |= Number(w.head) << i;
    w = w.tail;
  }
  return x >>> 0;
}

function u32_to_word(x) {
  let w = {$: "WNil"};
  for (let i = 31; i >= 0; i--) {
    w = {$: "WCon", head: ((x >>> i) & 1) === 1, tail: w};
  }
  return w;
}

function cmp_new(a, b) {
  return {$: a < b ? "LT"
    : a === b ? "EQ" : "GT"};
}

function nat_divmod(a, b) {
  return b === 0n ? {$: "Tuple", fst: 0n, snd: a}
    : {$: "Tuple", fst: a / b, snd: a % b};
}

function nat_chk(n) {
  if (n > 281474976710655n) {
    throw "bend: a Nat past the largest immediate 2^48-1";
  }
  return n;
}

function f32_show(x) {
  if (x !== x) {
    return "nan";
  }
  if (!Number.isFinite(x) || Object.is(x, -0)) {
    return x < 0 ? "-inf"
      : x === 0 ? "-0" : "inf";
  }
  let s = "x";
  for (let p = 1; p <= 9 && Math.fround(Number(s)) !== x; p += 1) {
    s = String(Number(x.toExponential(p - 1)));
  }
  return s;
}

function f32_bits(x) {
  return new Uint32Array(new Float32Array([x]).buffer)[0];
}

function f32_from_bits(u) {
  return new Float32Array(new Uint32Array([u]).buffer)[0];
}

function f32_read(s) {
  const re = /^\s*[+-]?((\d+\.?\d*|\.\d+)(e[+-]?\d+)?|inf(inity)?|nan)$/i;
  const v = Number(s.replace(/inf\w*/i, "Infinity"));
  return re.test(s) ? {$: "Some", value: Math.fround(v)} : {$: "None"};
}

function char_new(code) {
  if (code > 0x10FFFF || (code >= 0xD800 && code <= 0xDFFF)) {
    throw "bend: " + code + " is not a Unicode scalar value";
  }
  return String.fromCodePoint(code);
}

// Array
// =====

function array_new(d, v) {
  if (d > 31n) {
    throw "bend: an array past the deepest block class 31";
  }
  return Array(2 ** Number(d)).fill(v);
}

function array_swap(a, i, v) {
  const at = i % a.length;
  const old = a[at];
  a[at] = v;
  return {$: "Tuple", fst: a, snd: old};
}

// Run
// ===

function run_jump(f, x) {
  return {$: "$JMP", f: f, x: x};
}

function run_tail(f, x) {
  return {$: "$JMP", f: f.j?.f === f ? f.j : f, x: [x]};
}

function run_clo(j) {
  const f = (x) => run_loop(j(x));
  f.j = j;
  j.f = f;
  return f;
}

function run_loop(r) {
  while (r !== null && typeof r === "object" && r.$ === "$JMP") {
    r = r.f(...r.x);
  }
  return r;
}

function run_lib(f, n) {
  return (...a) => a.length < n ? run_lib((...b) => f(...a, ...b), n - a.length)
    : run_loop(f(...a));
}
// Program
// =======

function $live$(h_0, now_0) {
  if (h_0.$ === "NoHolder") {
    return {$: "NoHolder"};
  } else {
    const account_0 = h_0.account;
    const lease_0 = h_0.lease;
    const fence_0 = h_0.fence;
    const expires_0 = h_0.expires;
    const account_1 = account_0;
    const lease_1 = lease_0;
    const fence_1 = fence_0;
    const expires_1 = expires_0;
    return run_jump($Bool$pick$, [run_loop($Nat$is_gt$(expires_1, now_0)), {$: "Held", ["account"]: account_1, ["lease"]: lease_1, ["fence"]: fence_1, ["expires"]: expires_1}, {$: "NoHolder"}]);
  }
}

function $owns$(account_0, lease_0, h_0) {
  if (h_0.$ === "NoHolder") {
    return false;
  } else {
    const a_0 = h_0.account;
    const l_0 = h_0.lease;
    const f_0 = h_0.fence;
    const e_0 = h_0.expires;
    const a_1 = a_0;
    const l_1 = l_0;
    return run_jump($Bool$and$, [run_loop($Nat$is_eq$(account_0, a_1)), run_loop($Nat$is_eq$(lease_0, l_1))]);
  }
}

function $fence_of$(h_0) {
  if (h_0.$ === "NoHolder") {
    return 0n;
  } else {
    const a_0 = h_0.account;
    const l_0 = h_0.lease;
    const f_0 = h_0.fence;
    const e_0 = h_0.expires;
    const f_1 = f_0;
    return f_1;
  }
}

function $judge$claim$(h_0, account_0, op_0, lease_ms_0, cursor_0, now_0) {
  if (h_0.$ === "NoHolder") {
    return {$: "Applied", ["holder"]: {$: "Held", ["account"]: account_0, ["lease"]: op_0, ["fence"]: cursor_0, ["expires"]: nat_chk(now_0 + lease_ms_0)}};
  } else {
    const a_0 = h_0.account;
    const l_0 = h_0.lease;
    const f_0 = h_0.fence;
    const e_0 = h_0.expires;
    return {$: "Held_by_another"};
  }
}

function $judge$owned$(ok_0, fenced_0, after_0) {
  if (!ok_0) {
    return {$: "Not_the_holder"};
  } else {
    if (!fenced_0) {
      return {$: "Fence_mismatch"};
    } else {
      return {$: "Applied", ["holder"]: after_0};
    }
  }
}

function $judge$break$(human_0, stored_0) {
  if (!human_0) {
    return {$: "Not_human"};
  } else {
    if (stored_0.$ === "NoHolder") {
      return {$: "Nothing_to_break"};
    } else {
      const a_0 = stored_0.account;
      const l_0 = stored_0.lease;
      const f_0 = stored_0.fence;
      const e_0 = stored_0.expires;
      return {$: "Applied", ["holder"]: {$: "NoHolder"}};
    }
  }
}

function $judge$(a_0, stored_0, cursor_0, now_0) {
  if (a_0.$ === "Claim") {
    const account_0 = a_0.account;
    const op_0 = a_0.op;
    const lease_ms_0 = a_0.lease_ms;
    const account_1 = account_0;
    const op_1 = op_0;
    const lease_ms_1 = lease_ms_0;
    return run_jump($judge$claim$, [run_loop($live$(stored_0, now_0)), account_1, op_1, lease_ms_1, cursor_0, now_0]);
  } else if (a_0.$ === "Renew") {
    const account_2 = a_0.account;
    const lease_0 = a_0.lease;
    const fence_0 = a_0.fence;
    const lease_ms_2 = a_0.lease_ms;
    const account_3 = account_2;
    const lease_1 = lease_0;
    const fence_1 = fence_0;
    const lease_ms_3 = lease_ms_2;
    return run_jump($judge$owned$, [run_loop($owns$(account_3, lease_1, run_loop($live$(stored_0, now_0)))), run_loop($Nat$is_eq$(fence_1, run_loop($fence_of$(run_loop($live$(stored_0, now_0)))))), {$: "Held", ["account"]: account_3, ["lease"]: lease_1, ["fence"]: cursor_0, ["expires"]: nat_chk(now_0 + lease_ms_3)}]);
  } else if (a_0.$ === "Release") {
    const account_4 = a_0.account;
    const lease_2 = a_0.lease;
    const fence_2 = a_0.fence;
    const account_5 = account_4;
    const lease_3 = lease_2;
    const fence_3 = fence_2;
    return run_jump($judge$owned$, [run_loop($owns$(account_5, lease_3, run_loop($live$(stored_0, now_0)))), run_loop($Nat$is_eq$(fence_3, run_loop($fence_of$(run_loop($live$(stored_0, now_0)))))), {$: "NoHolder"}]);
  } else if (a_0.$ === "Break") {
    const human_0 = a_0.human;
    return run_jump($judge$break$, [human_0, run_loop($live$(stored_0, now_0))]);
  } else {
    return {$: "Applied", ["holder"]: stored_0};
  }
}

function $after$(v_0, stored_0) {
  if (v_0.$ === "Applied") {
    const h_0 = v_0.holder;
    return h_0;
  } else if (v_0.$ === "Held_by_another") {
    return stored_0;
  } else if (v_0.$ === "Not_the_holder") {
    return stored_0;
  } else if (v_0.$ === "Fence_mismatch") {
    return stored_0;
  } else if (v_0.$ === "Not_human") {
    return stored_0;
  } else {
    return stored_0;
  }
}

function $Bool$pick$(c_0, a_0, b_0) {
  if (!c_0) {
    return b_0;
  } else {
    return a_0;
  }
}

function $Nat$is_gt$(a_0, b_0) {
  return run_jump($Cmp$is_gt$, [cmp_new(a_0, b_0)]);
}

function $Bool$and$(a_0, b_0) {
  if (!a_0) {
    return false;
  } else {
    return b_0;
  }
}

function $Nat$is_eq$(a_0, b_0) {
  return run_jump($Cmp$is_eq$, [cmp_new(a_0, b_0)]);
}

function $Cmp$is_gt$(c_0) {
  if (c_0.$ === "LT") {
    return false;
  } else if (c_0.$ === "EQ") {
    return false;
  } else {
    return true;
  }
}

function $Cmp$is_eq$(c_0) {
  if (c_0.$ === "LT") {
    return false;
  } else if (c_0.$ === "EQ") {
    return true;
  } else {
    return false;
  }
}
export default {
  "live": run_lib($live$, 2),
  "owns": run_lib($owns$, 3),
  "fence_of": run_lib($fence_of$, 1),
  "judge.claim": run_lib($judge$claim$, 6),
  "judge.owned": run_lib($judge$owned$, 3),
  "judge.break": run_lib($judge$break$, 2),
  "judge": run_lib($judge$, 4),
  "after": run_lib($after$, 2),
};
