// @ts-nocheck: generated code, not type-checked; the source is proved instead.
// GENERATED by spec/build-kernel.ts from spec/settlement.bend; do not edit.
// The laws in spec/SETTLEMENT-LAWS.bend are proved over that source by the Bend 2 checker
// (spec/SETTLEMENT-PROOF.bend, gate string `All terms check.`) before this file is emitted.
// Bend 2; exports: Fact.eq, standing, is_exhibit, coordination_free, apply.
function word_to_u32(w) {
  let x = 0;
  for (let i = 0; w.$ === "WCon"; i++) {
    x |= Number(w.head) << i;
    w = w.tail;
  }
  return x >>> 0;
}

function u32_to_word(x) {
  let w = {$: "WNil"};
  for (let i = 31; i >= 0; i--) {
    w = {$: "WCon", head: ((x >>> i) & 1) === 1, tail: w};
  }
  return w;
}

function cmp_new(a, b) {
  return {$: a < b ? "LT"
    : a === b ? "EQ" : "GT"};
}

function nat_divmod(a, b) {
  return b === 0n ? {$: "Tuple", fst: 0n, snd: a}
    : {$: "Tuple", fst: a / b, snd: a % b};
}

function nat_chk(n) {
  if (n > 281474976710655n) {
    throw "bend: a Nat past the largest immediate 2^48-1";
  }
  return n;
}

function f32_show(x) {
  if (x !== x) {
    return "nan";
  }
  if (!Number.isFinite(x) || Object.is(x, -0)) {
    return x < 0 ? "-inf"
      : x === 0 ? "-0" : "inf";
  }
  let s = "x";
  for (let p = 1; p <= 9 && Math.fround(Number(s)) !== x; p += 1) {
    s = String(Number(x.toExponential(p - 1)));
  }
  return s;
}

function f32_bits(x) {
  return new Uint32Array(new Float32Array([x]).buffer)[0];
}

function f32_from_bits(u) {
  return new Float32Array(new Uint32Array([u]).buffer)[0];
}

function f32_read(s) {
  const re = /^\s*[+-]?((\d+\.?\d*|\.\d+)(e[+-]?\d+)?|inf(inity)?|nan)$/i;
  const v = Number(s.replace(/inf\w*/i, "Infinity"));
  return re.test(s) ? {$: "Some", value: Math.fround(v)} : {$: "None"};
}

function char_new(code) {
  if (code > 0x10FFFF || (code >= 0xD800 && code <= 0xDFFF)) {
    throw "bend: " + code + " is not a Unicode scalar value";
  }
  return String.fromCodePoint(code);
}

// Array
// =====

function array_new(d, v) {
  if (d > 31n) {
    throw "bend: an array past the deepest block class 31";
  }
  return Array(2 ** Number(d)).fill(v);
}

function array_swap(a, i, v) {
  const at = i % a.length;
  const old = a[at];
  a[at] = v;
  return {$: "Tuple", fst: a, snd: old};
}

// Run
// ===

function run_jump(f, x) {
  return {$: "$JMP", f: f, x: x};
}

function run_tail(f, x) {
  return {$: "$JMP", f: f.j?.f === f ? f.j : f, x: [x]};
}

function run_clo(j) {
  const f = (x) => run_loop(j(x));
  f.j = j;
  j.f = f;
  return f;
}

function run_loop(r) {
  while (r !== null && typeof r === "object" && r.$ === "$JMP") {
    r = r.f(...r.x);
  }
  return r;
}

function run_lib(f, n) {
  return (...a) => a.length < n ? run_lib((...b) => f(...a, ...b), n - a.length)
    : run_loop(f(...a));
}
// Program
// =======

function $Fact$eq$(a_0, b_0) {
  const x_0 = a_0.id;
  const y_0 = b_0.id;
  return run_jump($Nat$is_eq$, [x_0, y_0]);
}

function $standing$(l_0, f_0) {
  if (l_0.$ === "Nil") {
    return false;
  } else {
    const _t_0 = l_0.head;
    if (_t_0.$ === "Assert") {
      const g_0 = _t_0.fact;
      const rest_0 = l_0.tail;
      return run_jump($Bool$pick$, [run_loop($Fact$eq$(g_0, f_0)), true, run_loop($standing$(rest_0, f_0))]);
    } else if (_t_0.$ === "Allocate") {
      const n_0 = _t_0.count;
      const rest_1 = l_0.tail;
      return run_jump($standing$, [rest_1, f_0]);
    } else {
      const g_1 = _t_0.fact;
      const s_0 = _t_0.step;
      const rest_2 = l_0.tail;
      return run_jump($Bool$pick$, [run_loop($Fact$eq$(g_1, f_0)), false, run_loop($standing$(rest_2, f_0))]);
    }
  }
}

function $is_exhibit$(e_0) {
  if (e_0.$ === "Assert") {
    const g_0 = e_0.fact;
    return true;
  } else if (e_0.$ === "Allocate") {
    const n_0 = e_0.count;
    return false;
  } else {
    const g_1 = e_0.fact;
    const s_0 = e_0.step;
    return false;
  }
}

function $coordination_free$(es_0) {
  if (es_0.$ === "Nil") {
    return true;
  } else {
    const _t_0 = es_0.head;
    if (_t_0.$ === "Assert") {
      const g_0 = _t_0.fact;
      const rest_0 = es_0.tail;
      return run_jump($coordination_free$, [rest_0]);
    } else if (_t_0.$ === "Allocate") {
      const n_0 = _t_0.count;
      const rest_1 = es_0.tail;
      return run_jump($coordination_free$, [rest_1]);
    } else {
      const g_1 = _t_0.fact;
      const s_0 = _t_0.step;
      const rest_2 = es_0.tail;
      return false;
    }
  }
}

function $apply$(es_0, l_0) {
  if (es_0.$ === "Nil") {
    return l_0;
  } else {
    const e_0 = es_0.head;
    const rest_0 = es_0.tail;
    return run_jump($apply$, [rest_0, {$: "Con", ["head"]: e_0, ["tail"]: l_0}]);
  }
}

function $Nat$is_eq$(a_0, b_0) {
  return run_jump($Cmp$is_eq$, [cmp_new(a_0, b_0)]);
}

function $Bool$pick$(c_0, a_0, b_0) {
  if (!c_0) {
    return b_0;
  } else {
    return a_0;
  }
}

function $Cmp$is_eq$(c_0) {
  if (c_0.$ === "LT") {
    return false;
  } else if (c_0.$ === "EQ") {
    return true;
  } else {
    return false;
  }
}
export default {
  "Fact.eq": run_lib($Fact$eq$, 2),
  "standing": run_lib($standing$, 2),
  "is_exhibit": run_lib($is_exhibit$, 1),
  "coordination_free": run_lib($coordination_free$, 1),
  "apply": run_lib($apply$, 2),
};
